# shortcuts for running scripts

name: scripts_shrtct

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  orm: ^3.4.6  
  build_runner:  
  json_serializable:
  json_annotation:


scripts:
  gen: "dart g_transaction_types.dart && dart g_operators.dart && dart g_users.dart && dart g_accounts.dart"
  gen-a: "dart g_accounts.dart"
  gen-u: "dart g_users.dart"
  gen-t: "dart g_transaction_types.dart"  
  prisma-push: "npx prisma db push"
  prisma-gen: "npx prisma generate && dart run build_runner build"
  prisma-pg: "npx prisma db push && npx prisma generate && dart run build_runner build"
