name: gen

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build_runner: ^2.4.7
  http: ^1.1.2
  orm: ^4.0.0-alpha.4


# shortcuts for running scripts
scripts:
  a: "git add ."
  p: "git push -u origin master"
  prisma-pg: "npx prisma db push && npx prisma generate && dart run build_runner build"
  prisma-gen: "npx prisma generate && dart run build_runner build"
  prisma-push: "npx prisma db push"
