# shortcuts for running scripts

name: scripts_shrtct

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build_runner: ^2.4.7
  http: ^1.1.2
  orm: ^4.0.0-alpha.0


scripts:
  gen: "dart g_transaction_types.dart && dart g_operators.dart && dart g_users.dart && dart g_accounts.dart && dart g_transactions.dart"
  gen-a: "dart g_accounts.dart"
  gen-u: "dart g_users.dart"
  gen-o: "dart g_operators.dart"
  gen-t: "dart g_transactions.dart"  
  gen-tt: "dart g_transaction_types.dart"  
  prisma-push: "npx prisma db push"
  get-add: "git add ."
  get-push: "git push -u origin master"
  prisma-gen: "npx prisma generate && dart run build_runner build"
  prisma-pg: "npx prisma db push && npx prisma generate && dart run build_runner build"
