name: gen

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0
  orm: ^4.0.0-alpha.4


# shortcuts for running scripts
scripts:
  prisma-push: "npx prisma db push"
  prisma-gen: "npx prisma generate"
