# shortcuts for running scripts

name: scripts_shrtct

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  orm: ^3.4.6  
  build_runner:  
  json_serializable:
  json_annotation:


scripts:
  gen: "dart generator.dart"
  prisma-push: "npx prisma db push"
  prisma-gen: "npx prisma generate && dart run build_runner build"
